$ANSIBLE_VAULT;1.1;AES256
39663534613033383064313336343733393261376430383636346563356432653766313831613930
6434393862613136313865373237346365396633373466390a656236346132643532626564313839
31373137343633326533333132346262353462303966363130636632333635666161633636316336
3536333066386433380a313162353230663364366338656664663865613139323430393638663532
31326261643236306236396464396566653734646630333566333231643261336238386436633166
63396330343765376639643937323666663261633262376239626163373430633734663936633436
36303266393565363230646665653939636536666234646531303131633436363035656235396639
36623232343331353538316434393934393439653232383332343635626464366664653839313931
37333830353461643863326537353266613161313366396239646231303732636531
